[package]
name = "secure_env"
version = "0.1.0"
authors = ["Remo Zumsteg <remolueoend@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
